### ISSUE TITLE
機能提案：コメント欄を折りたたんで表示

### ISSUE THREAD

**Issue by munierujp** [munierujp/qiita-team-plus#20]
![画面収録 2020-02-15 22 14 17 mov](https://user-images.githubusercontent.com/20086673/74588512-9e2b7a80-5040-11ea-8057-61aced6df2b2.gif)

```html
<div class="teamSidebarContainer_main">
  <article class="teamArticle">...</article>
  <details>
    <summary data-qiita-team-plus-foldable-comments="comment-summary">
      <i class="fa fa-comments mr-1"></i>
      <span>コメント ({{comments.length}})</span>
    </summary>
    <div class="itemsShowComment">...</div>
  </details>
</div>
```

```css
[data-qiita-team-plus-foldable-comments="comment-summary"] {
  cursor: pointer;
  outline: none;
  font-size: 16px;
  margin-top: 8px;
  margin-left: 8px;
}
```

https://developer.mozilla.org/ja/docs/Web/HTML/Element/details
