### ISSUE TITLE
機能提案：古い記事にアラートを表示

### ISSUE THREAD

**Issue by munierujp** [munierujp/qiita-team-plus#32]
Qiitaのように、最終更新からしばらく経っている記事にアラートを表示する。

## 参考
Qiitaの場合

<img width="881" alt="スクリーンショット 2020-02-22 15 23 25" src="https://user-images.githubusercontent.com/20086673/75087729-4d0f0f80-5587-11ea-8efc-14db3edef7cc.png">

```html
<div class="it-DeprecationAlert_one mb-5 p-2"><span class="fa fa-warning mr-1"></span>この記事は最終更新日から1年以上が経過しています。</div>
```

```html
<div class="it-DeprecationAlert_three mb-5 p-2"><span class="fa fa-warning mr-1"></span>この記事は最終更新日から3年以上が経過しています。</div>
```

```html
<div class="it-DeprecationAlert_five mb-5 p-2"><span class="fa fa-warning mr-1"></span>この記事は最終更新日から5年以上が経過しています。</div>
```

```css
.mb-5 {
    margin-bottom: 40px;
}

.p-2 {
    padding: 16px;
}

.it-DeprecationAlert_one {
  background-color: #fff3cd;
  color: #856404
}

.it-DeprecationAlert_three {
  background-color: #ffe79a;
  color: #533f03
}

.it-DeprecationAlert_five {
  background-color: #ffdb67;
  color: #221a01
}

.mr-1 {
    margin-right: 8px;
}

.fa {
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```
